<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWyOWgV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWyOWgV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFWyOWgV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFWyOWgV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFWyOWgV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FWyOWgV',
    'container.build_id' => '4b939018',
    'container.build_time' => 1566170861,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWyOWgV');
